apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-exporter
  namespace: monitoring
  labels:
    app: ingress-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ingress-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingress-exporter
    spec:
      containers:
      - name: ingress-exporter
        image: quay.io/giantswarm/ingress-exporter:[[ .SHA ]]
        livenessProbe:
          httpGet:
            path: /
            port: 9410
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi
        ports:
          - name: http
            containerPort: 9410
      imagePullSecrets:
      - name: vault-exporter-pull-secret
