apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-exporter
  namespace: monitoring
  labels:
    app: ingress-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ingress-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        releasetime: {{ $.Release.Time }}
      labels:
        app: ingress-exporter
    spec:
      containers:
      - name: ingress-exporter
        image: quay.io/giantswarm/ingress-exporter:[[ .SHA ]]
        args:
        - daemon
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi
        ports:
          - name: http
            containerPort: 8000
      imagePullSecrets:
      - name: ingress-exporter-pull-secret
