apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-exporter
  namespace: monitoring
  labels:
    app: ingress-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ingress-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        releasetime: {{ $.Release.Time }}
      labels:
        app: ingress-exporter
    spec:
      volumes:
        - name: ingress-exporter-configmap
          configMap:
            name: ingress-exporter-configmap
            items:
              - key: config.yaml
                path: config.yaml
      containers:
      - name: ingress-exporter
        image: quay.io/giantswarm/ingress-exporter:[[ .SHA ]]
        volumeMounts:
          - name: ingress-exporter-configmap
            mountPath: /var/run/ingress-exporter/configmap/
        args:
        - daemon
        - --config.dirs=/var/run/ingress-exporter/configmap/
        - --config.files=config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi
        ports:
          - name: http
            containerPort: 8000
      serviceAccountName: ingress-exporter
      imagePullSecrets:
      - name: ingress-exporter-pull-secret
