version: 2.1
orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: ingress-exporter
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          name: push-to-control-plane-app-catalog
          context: architect
          chart: ingress-exporter
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          filters:
            tags:
              only: /^v.*/
          requires:
            - push-to-registries
