version: 2.1

orbs:
  architect: giantswarm/architect@4.28.1

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: ingress-exporter
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-quay
          image: quay.io/giantswarm/ingress-exporter
          username_envar: QUAY_USERNAME
          password_envar: QUAY_PASSWORD
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          chart: ingress-exporter
          requires:
            - push-to-quay
          filters:
            tags:
              only: /^v.*/
