version: 2.1

orbs:
  architect: giantswarm/architect@4.8.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: ingress-exporter
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-ingress-exporter-to-quay
          image: "quay.io/giantswarm/ingress-exporter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-ingress-exporter-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "ingress-exporter"
          requires:
            - push-ingress-exporter-to-quay
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-ingress-exporter-to-kvm-app-collection
          app_name: "ingress-exporter"
          app_namespace: "monitoring"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-ingress-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
