version: 2.1
orbs:
  architect: giantswarm/architect@4.33.1

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: ingress-exporter
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-quay
          context: architect
          image: quay.io/giantswarm/ingress-exporter
          username_envar: QUAY_USERNAME
          password_envar: QUAY_PASSWORD
          filters:
            tags:
              only: /^v.*/
          requires:
            - go-build

      - architect/push-to-app-catalog:
          name: push-to-control-plane-app-catalog
          context: architect
          chart: ingress-exporter
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          filters:
            tags:
              only: /^v.*/
          requires:
            - push-to-quay
