name: ingress-exporter
namespace: monitoring
image:
  repository: "giantswarm/ingress-exporter"
  tag: "[[ .Version ]]"

userID: 1000
groupID: 1000

registry:
  domain: gsoci.azurecr.io
  pullSecret:
    dockerConfigJSON: ""

global:
  podSecurityStandards:
    enforced: true
