apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        app: {{ .Values.name }}
    spec:
      volumes:
        - name: ingress-exporter-configmap
          configMap:
            name: ingress-exporter-configmap
            items:
              - key: config.yaml
                path: config.yaml
      serviceAccountName: ingress-exporter
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      containers:
      - name: {{ .Values.name }}
        image: "quay.io/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        volumeMounts:
          - name: ingress-exporter-configmap
            mountPath: /var/run/ingress-exporter/configmap/
        args:
        - daemon
        - --config.dirs=/var/run/ingress-exporter/configmap/
        - --config.files=config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi
        ports:
          - name: http
            containerPort: 8000
      imagePullSecrets:
      - name: ingress-exporter-pull-secret
