apiVersion: v1
kind: Service
metadata:
  name: ingress-exporter
  namespace: monitoring
  labels:
    app: ingress-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - name: ingress-exporter
    port: 8000
    targetPort: 8000
  selector:
    app: ingress-exporter
